import { randomBytes, scrypt as nodeScrypt, timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import { Router, type Router as RouterType } from "express";
import { z } from "zod";
import { pool } from "../db/pool.js";
import { authenticate, hashToken, requirePermission, type AuthenticatedRequest } from "../middleware/authorization.js";

const scrypt = promisify(nodeScrypt);
const router: RouterType = Router();
const loginSchema = z.object({ identity: z.string().min(1), password: z.string().min(1) });
const userSchema = z.object({ firstName: z.string().min(1), lastName: z.string().default(""), username: z.string().min(3), email: z.string().email(), password: z.string().min(12), roleId: z.string().uuid() });
const roleSchema = z.object({ name: z.string().min(2), description: z.string().optional() });
const permissionSchema = z.object({ permissionIds: z.array(z.string().uuid()), scope: z.enum(["all", "branch", "warehouse", "own", "team"]).default("all") });

async function hashPassword(password: string) { const salt = randomBytes(16).toString("hex"); const derived = await scrypt(password, salt, 64) as Buffer; return `scrypt:${salt}:${derived.toString("hex")}`; }
async function verifyPassword(password: string, stored: string) { const [, salt, encoded] = stored.split(":"); if (!salt || !encoded) return false; const actual = await scrypt(password, salt, 64) as Buffer; const expected = Buffer.from(encoded, "hex"); return expected.length === actual.length && timingSafeEqual(expected, actual); }
function unavailable(res: any) { return !pool && res.status(503).json({ success: false, message: "DATABASE_URL is not configured" }); }

router.post("/api/auth/login", async (req, res, next) => {
  const parsed = loginSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, message: "Identity and password are required" }); if (unavailable(res)) return;
  try {
    let { rows } = await pool!.query("select * from users where lower(email) = lower($1) or lower(username) = lower($1) limit 1", [parsed.data.identity]);
    // Bootstrap creates one admin only when explicitly configured for the first deployment.
    const bootstrap = [
      { email: process.env.BOOTSTRAP_ADMIN_EMAIL, password: process.env.BOOTSTRAP_ADMIN_PASSWORD, role: process.env.BOOTSTRAP_ADMIN_ROLE || 'Master Admin' },
      { email: process.env.BOOTSTRAP_MASTER_EMAIL, password: process.env.BOOTSTRAP_MASTER_PASSWORD, role: 'Master Admin' },
    ].find((candidate) => candidate.email && candidate.password && candidate.email.toLowerCase() === parsed.data.identity.toLowerCase() && candidate.password === parsed.data.password);
    if (!rows[0] && bootstrap) {
      const role = await pool!.query("select id from roles where name = $1 limit 1", [bootstrap.role]);
      if (!role.rows[0]) return res.status(503).json({ success: false, message: "Run the database migrations before signing in" });
      const isMaster = bootstrap.role === 'Master Admin';
      const created = await pool!.query("insert into users (name, first_name, username, email, password_hash, role_id) values ($1,$2,$3,$4,$5,$6) returning *", [isMaster ? "Master Admin" : "Manager", isMaster ? "Master" : "Manager", isMaster ? "master.admin.control" : "manager", bootstrap.email, await hashPassword(bootstrap.password!), role.rows[0].id]);
      await pool!.query("insert into user_roles (user_id, role_id) values ($1,$2)", [created.rows[0].id, role.rows[0].id]);
      rows = [created.rows[0]];
    }
    const user = rows[0];
    if (!user || user.status !== "Active" || (user.account_expires_at && new Date(user.account_expires_at) <= new Date()) || !(await verifyPassword(parsed.data.password, user.password_hash))) return res.status(401).json({ success: false, message: "Invalid credentials" });
    const rawToken = randomBytes(32).toString("base64url");
    const session = await pool!.query("insert into sessions (user_id, token_hash, device, browser, ip_address, expires_at) values ($1,$2,$3,$4,$5,now() + interval '8 hours') returning id, expires_at", [user.id, hashToken(rawToken), req.headers["user-agent"]?.slice(0, 255), req.headers["user-agent"]?.slice(0, 255), req.ip]);
    await pool!.query("update users set last_login = now(), updated_at = now() where id = $1", [user.id]);
    await pool!.query("insert into activity_logs (user_id, module, action, status, ip_address, device_info, remarks) values ($1, 'Authentication', 'Login', 'Success', $2, $3, 'Session created')", [user.id, req.ip, req.headers["user-agent"]?.slice(0, 255)]);
    res.json({ success: true, data: { token: rawToken, sessionId: session.rows[0].id, expiresAt: session.rows[0].expires_at } });
  } catch (error) { next(error); }
});

router.post("/api/auth/logout", authenticate, async (req: AuthenticatedRequest, res, next) => { try { await pool!.query("update sessions set revoked_at = now() where id = $1", [req.auth!.sessionId]); if (req.auth!.userId) await pool!.query("insert into activity_logs (user_id, module, action, status, remarks) values ($1, 'Authentication', 'Logout', 'Success', 'Session revoked by user')", [req.auth!.userId]); res.json({ success: true }); } catch (error) { next(error); } });
router.get("/api/auth/me", authenticate, async (req: AuthenticatedRequest, res, next) => { try { const { rows } = await pool!.query("select u.id, u.first_name, u.last_name, u.name, u.username, u.email, u.status, u.last_login, u.created_at, coalesce((select json_agg(json_build_object('id', r.id, 'name', r.name)) from user_roles ur join roles r on r.id = ur.role_id where ur.user_id = u.id), '[]') roles from users u where u.id = $1", [req.auth!.userId]); res.json({ success: true, data: { ...rows[0], permissions: [...req.auth!.permissions] } }); } catch (error) { next(error); } });

router.get("/api/users", authenticate, requirePermission("system.users.view"), async (_req, res, next) => { try { const { rows } = await pool!.query("select u.id, u.first_name, u.last_name, u.name, u.username, u.email, u.status, u.last_login, u.created_at, coalesce((select r.name from user_roles ur join roles r on r.id = ur.role_id where ur.user_id = u.id limit 1), 'Unassigned') role from users u order by u.created_at desc"); res.json({ success: true, data: rows }); } catch (error) { next(error); } });
router.post("/api/users", authenticate, requirePermission("system.users.create"), async (req: AuthenticatedRequest, res, next) => { const parsed = userSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, message: "Invalid user payload", issues: parsed.error.issues }); try { const user = parsed.data; const role = await pool!.query("select id from roles where id = $1", [user.roleId]); if (!role.rows[0]) return res.status(400).json({ success: false, message: "Role not found" }); const passwordHash = await hashPassword(user.password); const created = await pool!.query("insert into users (name, first_name, last_name, username, email, password_hash, role_id) values ($1,$2,$3,$4,$5,$6,$7) returning id, name, first_name, last_name, username, email, status, created_at", [`${user.firstName} ${user.lastName}`.trim(), user.firstName, user.lastName, user.username, user.email, passwordHash, user.roleId]); await pool!.query("insert into user_roles (user_id, role_id) values ($1,$2)", [created.rows[0].id, user.roleId]); await pool!.query("insert into activity_logs (user_id, module, action, record_id, record_type, new_value) values ($1,'System','Created user',$2,'User',$3)", [req.auth!.userId, created.rows[0].id, JSON.stringify({ username: user.username, roleId: user.roleId })]); res.status(201).json({ success: true, data: created.rows[0] }); } catch (error) { next(error); } });
router.post("/api/users/:id/revoke-sessions", authenticate, requirePermission("system.users.edit"), async (req: AuthenticatedRequest, res, next) => { try { await pool!.query("update sessions set revoked_at = now() where user_id = $1 and revoked_at is null", [req.params.id]); await pool!.query("insert into activity_logs (user_id, module, action, record_id, record_type) values ($1,'System','Revoked sessions',$2,'User')", [req.auth!.userId, req.params.id]); res.json({ success: true }); } catch (error) { next(error); } });
router.post("/api/users/:id/activate", authenticate, requirePermission("system.users.disable"), async (req: AuthenticatedRequest, res, next) => { try { const { rows } = await pool!.query("update users set status = 'Active', updated_at = now() where id = $1 returning id, status", [req.params.id]); if (!rows[0]) return res.status(404).json({ success: false, message: "User not found" }); await pool!.query("insert into activity_logs (user_id, module, action, record_id, record_type, new_value) values ($1,'System','Activated user',$2,'User',$3)", [req.auth!.userId, req.params.id, JSON.stringify({ status: "Active" })]); res.json({ success: true, data: rows[0] }); } catch (error) { next(error); } });
router.post("/api/users/:id/deactivate", authenticate, requirePermission("system.users.disable"), async (req: AuthenticatedRequest, res, next) => { try { if (req.params.id === req.auth!.userId) return res.status(400).json({ success: false, message: "You cannot deactivate your own account" }); const { rows } = await pool!.query("update users set status = 'Inactive', updated_at = now() where id = $1 returning id, status", [req.params.id]); if (!rows[0]) return res.status(404).json({ success: false, message: "User not found" }); await pool!.query("update sessions set revoked_at = now() where user_id = $1 and revoked_at is null", [req.params.id]); await pool!.query("insert into activity_logs (user_id, module, action, record_id, record_type, new_value) values ($1,'System','Deactivated user',$2,'User',$3)", [req.auth!.userId, req.params.id, JSON.stringify({ status: "Inactive" })]); res.json({ success: true, data: rows[0] }); } catch (error) { next(error); } });

router.get("/api/roles", authenticate, requirePermission("system.roles.view"), async (_req, res, next) => { try { const { rows } = await pool!.query("select r.*, count(distinct ur.user_id)::int user_count, count(distinct rp.permission_id)::int permission_count, coalesce((select jsonb_object_agg(grouped.module, grouped.actions) from (select p.module, jsonb_agg(p.action order by p.action) actions from role_permissions rp2 join permissions p on p.id = rp2.permission_id where rp2.role_id = r.id group by p.module) grouped), '{}'::jsonb) permissions from roles r left join user_roles ur on ur.role_id = r.id left join role_permissions rp on rp.role_id = r.id group by r.id order by r.name"); res.json({ success: true, data: rows }); } catch (error) { next(error); } });
router.post("/api/roles", authenticate, requirePermission("system.roles.create"), async (req: AuthenticatedRequest, res, next) => { const parsed = roleSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, message: "Invalid role payload", issues: parsed.error.issues }); try { const { rows } = await pool!.query("insert into roles (name, description) values ($1,$2) returning *", [parsed.data.name, parsed.data.description ?? null]); await pool!.query("insert into activity_logs (user_id, module, action, record_id, record_type, new_value) values ($1,'System','Created role',$2,'Role',$3)", [req.auth!.userId, rows[0].id, JSON.stringify({ name: rows[0].name })]); res.status(201).json({ success: true, data: rows[0] }); } catch (error) { next(error); } });
router.get("/api/roles/:id/permissions", authenticate, requirePermission("system.roles.view"), async (req, res, next) => { try { const { rows } = await pool!.query("select p.*, rp.scope from role_permissions rp join permissions p on p.id = rp.permission_id where rp.role_id = $1 order by p.module, p.resource, p.action", [req.params.id]); res.json({ success: true, data: rows }); } catch (error) { next(error); } });
router.put("/api/roles/:id/permissions", authenticate, requirePermission("system.permissions.manage"), async (req: AuthenticatedRequest, res, next) => { const parsed = permissionSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, message: "Invalid permission payload", issues: parsed.error.issues }); const client = await pool!.connect(); try { await client.query("begin"); await client.query("delete from role_permissions where role_id = $1", [req.params.id]); if (parsed.data.permissionIds.length) await client.query("insert into role_permissions (role_id, permission_id, scope) select $1, unnest($2::uuid[]), $3", [req.params.id, parsed.data.permissionIds, parsed.data.scope]); await client.query("insert into activity_logs (user_id, module, action, record_id, record_type, new_value) values ($1,'System','Changed role permissions',$2,'Role',$3)", [req.auth!.userId, req.params.id, JSON.stringify(parsed.data)]); await client.query("commit"); res.json({ success: true }); } catch (error) { await client.query("rollback"); next(error); } finally { client.release(); } });
router.get("/api/permissions", authenticate, requirePermission("system.permissions.view"), async (_req, res, next) => { try { const { rows } = await pool!.query("select * from permissions order by module, resource, action"); res.json({ success: true, data: rows }); } catch (error) { next(error); } });
router.get("/api/users/:id/sessions", authenticate, requirePermission("system.users.view"), async (_req, res, next) => { try { const { rows } = await pool!.query("select id, device, browser, ip_address, last_activity_at, expires_at, created_at from sessions where user_id = $1 and revoked_at is null order by created_at desc", [_req.params.id]); res.json({ success: true, data: rows }); } catch (error) { next(error); } });

export { router as identityRouter };
